language: python
python:
    - "3.3"
services:
    - mongodb
    - redis-server
    - rabbitmq
install:
    - "pip install -r requirements.txt"
    - "cp tapiriik/local_settings.py.example tapiriik/local_settings.py"
script: "python runtests.py"
sudo: false
